// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zUserDto = z.object({
    id: z.number().int().optional(),
    username: z.string().optional(),
    email: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional()
});

export const zCreateUserDto = z.object({
    username: z.string().optional(),
    password: z.string().optional(),
    email: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional()
});

export const zUserGetUsersResponse = z.array(zUserDto);

export const zUserCreateUserResponse = z.string();

export const zUserDeleteUserResponse = z.string();

export const zUserGetUserResponse = zUserDto;

export const zUserUpdateUserResponse = z.string();